### ISSUE TITLE
issues with grunt and phantom js

### ISSUE THREAD

**Issue by squarewave24** [gruntjs/grunt-lib-phantomjs#68]
I am running with different issues when trying to use phantom.js with grunt + jasmine. 

**package.json**

`"phantomjs": "~1.8.x",`

i get an error during `npm install`:

*events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
npm ERR! phantomjs@1.8.2-2 install: `node install.js`
npm ERR! Exit status 8*

**if i use a newer version:**

`"phantomjs": "1.9.1-7",`

the install works (installing 1.9.7), however, when i run my tests, I get the following error:

```
log: Requirejs error: message: Script error for: PhantomRunner
http://requirejs.org/docs/errors.html#scripterror

log: Requirejs error: requireType: scripterror

log: Requirejs error: requireModules: PhantomRunner

log: Requirejs error: originalError: [object Event]

log: =================

log: Requirejs error: returnValue: true

log: Requirejs error: timeStamp: 1409778621910

log: Requirejs error: eventPhase: 2

log: Requirejs error: target: [object HTMLScriptElement]

log: src, file:///C:/temp/Manager%20-%20Jasmine%20Demo/WebUI/PhantomRunner.js

log: Requirejs error: defaultPrevented: false

log: Requirejs error: srcElement: [object HTMLScriptElement]

log: src, file:///C:/temp/Manager%20-%20Jasmine%20Demo/WebUI/PhantomRunner.js

log: Requirejs error: type: error

log: Requirejs error: clipboardData: undefined

log: Requirejs error: cancelable: false

log: Requirejs error: currentTarget: [object HTMLScriptElement]

log: src, file:///C:/temp/Manager%20-%20Jasmine%20Demo/WebUI/PhantomRunner.js

log: Requirejs error: bubbles: false

log: Requirejs error: cancelBubble: false*
```

**note that if i go to specRunner.html all my tests work as expected.**

**Gruntfile.js:**

```json
module.exports = function (grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON("package.json"),
        watch: {
            grunt: {
                files: ["Gruntfile.js", "package.json"],
                tasks: "default"
            },
            javascript: {
                files: ["app/**/*.js", "app/**/**/*.js", "tests/spec/*Spec.js", "*.jshintrc"],
                tasks: "test"
            }
        },
        jasmine: {
            src: "tests/lib/jasmine-1.0.0/*.js",
            options: {
                specs: "tests/spec/*Spec.js",
                //host: "http://localhost:62310",
                template: require("grunt-template-jasmine-requirejs")
            }
        },
        jshint: {
            all: [
              "Gruntfile.js","app/**/*.js", "app/**/**/*.js"
            ],
            options: {
                jshintrc: "options.jshintrc"
            }
        },
        mochacli: {
            options: {
                reporter: "nyan",
                ui: "tdd"
            },
            all: ["tests/spec/*Spec.js"]
        }
        //,
        //qunit: {
        //    all: {
        //        options: {
        //            urls: [
        //              'http://localhost:62310/tests/specrunner.html'
        //            ]
        //        }
        //    }
        //}
    });
    grunt.loadNpmTasks('grunt-template-jasmine-requirejs');
    grunt.loadNpmTasks("grunt-contrib-watch");
    grunt.loadNpmTasks("grunt-contrib-jshint");
    grunt.loadNpmTasks("grunt-contrib-jasmine");
     grunt.loadNpmTasks("grunt-mocha-cli");
    grunt.registerTask("test", [
        "jshint"
        , "jasmine"
        //,"mochacli"
    ]);
    grunt.registerTask("default", ["test"]);
};
```

**Comment by Arkni** [comment]
AFAICT you already fixed your problem in Medium/phantomjs#219

Closing this for now, feel free to ask if you have followup questions.
