### ISSUE TITLE
Can't build grunt-lib-phantomjs with phantomjs-1.9.8

### ISSUE THREAD

**Issue by vecmezoni** [gruntjs/grunt-lib-phantomjs#72]
```
npm install grunt-lib-phantomjs
/
> phantomjs@1.9.14 install /home/hh/node_modules/grunt-lib-phantomjs/node_modules/phantomjs
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Download already available at /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Extracting tar contents (via spawned process)
Removing /home/hh/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1422373324671/phantomjs-1.9.8-linux-x86_64 -> /home/hh/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom
Writing location.js file
Phantom installation failed { [Error: ENOTDIR, not a directory '/home/hh/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs']
  errno: 27,
  code: 'ENOTDIR',
  path: '/home/hh/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs',
  syscall: 'chmod' } Error: ENOTDIR, not a directory '/home/hh/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs'
    at Object.fs.chmodSync (evalmachine.<anonymous>:821:18)
    at Object.chmodSync (/home/hh/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/fs-extra/node_modules/graceful-fs/polyfills.js:141:17)
    at Promise.validExit [as _successFn] (/home/hh/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:145:8)
    at Promise._call (/home/hh/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:373:13)
    at Promise._withInput (/home/hh/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:333:25)
    at Promise.resolve (/home/hh/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:105:27)
    at resolver (/home/hh/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:409:17)
    at CB (/home/hh/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/fs-extra/node_modules/rimraf/rimraf.js:68:5)
    at Object.oncomplete (fs.js:107:15)
npm ERR! phantomjs@1.9.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.14 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-56-generic
npm ERR! command "node" "/usr/bin/npm" "install" "grunt-lib-phantomjs"
npm ERR! cwd /home/hh
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.4.26
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/hh/npm-debug.log
npm ERR! not ok code 0
```

**Comment by vecmezoni** [comment]
Looks like it doesn't extract if from archive

**Comment by vecmezoni** [comment]
Somehow resolved, possibly some npm issues.
